insert into product (productid, productname, price, reducedprice) values (3, 'Rosemary - Fresh', 22.11, 2.211);
insert into product (productid, productname, price, reducedprice) values (4, 'Cleaner - Bleach', 49.78, 24.978);
insert into product (productid, productname, price, reducedprice) values (5, 'Lettuce - Radicchio', 23.34, 21.334);
insert into product (productid, productname, price, reducedprice) values (6, 'Bread Sour Rolls', 55.58, 11.558);
insert into product (productid, productname, price, reducedprice) values (7, 'Triple Sec - Mcguinness', 34.38, 23.438);
insert into product (productid, productname, price, reducedprice) values (8, 'Lettuce - Lolla Rosa', 68.99, 15.899);
insert into product (productid, productname, price, reducedprice) values (9, 'Veal - Knuckle', 68.22, 47.822);
insert into product (productid, productname, price, reducedprice) values (10, 'Skewers - Bamboo', 6.44, 0.644);
insert into product (productid, productname, price, reducedprice) values (11, 'Yeast Dry - Fermipan', 18.6, 13.86);
insert into product (productid, productname, price, reducedprice) values (12, 'Cut Wakame - Hanawakaba', 17.92, 2.792);
insert into product (productid, productname, price, reducedprice) values (13, 'Lidsoupcont Rp12dn', 23.08, 14.308);
insert into product (productid, productname, price, reducedprice) values (14, 'Mustard - Dijon', 98.36, 86.836);
insert into product (productid, productname, price, reducedprice) values (15, 'Filo Dough', 77.41, 19.741);
insert into product (productid, productname, price, reducedprice) values (16, 'Soup - Cream Of Broccoli', 51.16, 16.116);
insert into product (productid, productname, price, reducedprice) values (17, 'Everfresh Products', 22.85, 6.285);
insert into product (productid, productname, price, reducedprice) values (18, 'Irish Cream - Butterscotch', 16.3, 3.63);
insert into product (productid, productname, price, reducedprice) values (19, 'Beans - Kidney, Red Dry', 9.9, 2.99);
insert into product (productid, productname, price, reducedprice) values (20, 'Syrup - Pancake', 90.04, 66.004);
insert into product (productid, productname, price, reducedprice) values (21, 'Juice Peach Nectar', 94.62, 73.462);
insert into product (productid, productname, price, reducedprice) values (22, 'Turkey - Whole, Fresh', 47.87, 26.787);
insert into product (productid, productname, price, reducedprice) values (23, 'Orange - Tangerine', 11.48, 2.148);
insert into product (productid, productname, price, reducedprice) values (24, 'Cookie Dough - Chunky', 46.91, 7.691);
insert into product (productid, productname, price, reducedprice) values (25, 'Lettuce - Iceberg', 69.14, 62.914);
insert into product (productid, productname, price, reducedprice) values (26, 'Bread - Malt', 92.54, 14.254);
insert into product (productid, productname, price, reducedprice) values (27, 'Grapes - Green', 39.26, 26.926);
insert into product (productid, productname, price, reducedprice) values (28, 'Bread - Roll, Canadian Dinner', 23.58, 22.358);
insert into product (productid, productname, price, reducedprice) values (29, 'Potatoes - Purple, Organic', 22.23, 13.223);
insert into product (productid, productname, price, reducedprice) values (30, 'Beef - Cow Feet Split', 16.23, 8.623);
insert into product (productid, productname, price, reducedprice) values (31, 'Pork - Tenderloin, Frozen', 90.75, 49.075);
insert into product (productid, productname, price, reducedprice) values (32, 'Blouse / Shirt / Sweater', 38.22, 35.822);
insert into product (productid, productname, price, reducedprice) values (33, 'Coffee Cup 12oz 5342cd', 87.86, 24.786);
insert into product (productid, productname, price, reducedprice) values (34, 'Cookies - Englishbay Chochip', 17.88, 15.788);
insert into product (productid, productname, price, reducedprice) values (35, 'Soup - Campbells Bean Medley', 3.63, 1.363);
insert into product (productid, productname, price, reducedprice) values (36, 'Oyster - In Shell', 16.17, 9.617);
insert into product (productid, productname, price, reducedprice) values (37, 'Cookie - Oreo 100x2', 27.77, 10.777);
insert into product (productid, productname, price, reducedprice) values (38, 'Potatoes - Fingerling 4 Oz', 15.58, 14.558);
insert into product (productid, productname, price, reducedprice) values (39, 'Wine - Casillero Del Diablo', 88.79, 35.879);
insert into product (productid, productname, price, reducedprice) values (40, 'Soup - Campbells Asian Noodle', 11.16, 3.116);
insert into product (productid, productname, price, reducedprice) values (41, 'Cheese - Mozzarella', 16.45, 12.645);
insert into product (productid, productname, price, reducedprice) values (42, 'Jicama', 29.64, 4.964);
insert into product (productid, productname, price, reducedprice) values (43, 'Butter - Salted, Micro', 77.15, 40.715);
insert into product (productid, productname, price, reducedprice) values (44, 'Bouq All Italian - Primerba', 62.82, 59.282);
insert into product (productid, productname, price, reducedprice) values (45, 'Bread - Bagels, Mini', 83.37, 12.337);
insert into product (productid, productname, price, reducedprice) values (46, 'Creme De Cacao White', 20.72, 17.072);
insert into product (productid, productname, price, reducedprice) values (47, 'Ecolab - Ster Bac', 28.0, 22.8);
insert into product (productid, productname, price, reducedprice) values (48, 'Cinnamon - Stick', 32.01, 13.201);
insert into product (productid, productname, price, reducedprice) values (49, 'Dehydrated Kelp Kombo', 78.83, 21.883);
insert into product (productid, productname, price, reducedprice) values (50, 'Jolt Cola - Red Eye', 33.48, 32.348);
insert into product (productid, productname, price, reducedprice) values (51, 'Quail - Jumbo Boneless', 12.08, 6.208);
insert into product (productid, productname, price, reducedprice) values (52, 'Wine - Cava Aria Estate Brut', 66.33, 43.633);
insert into product (productid, productname, price, reducedprice) values (53, 'Water - Perrier', 53.8, 49.38);
insert into product (productid, productname, price, reducedprice) values (54, 'Wine - Gato Negro Cabernet', 5.93, 2.593);
insert into product (productid, productname, price, reducedprice) values (55, 'Napkin White', 80.42, 69.042);
insert into product (productid, productname, price, reducedprice) values (56, 'Towel Multifold', 74.96, 43.496);
insert into product (productid, productname, price, reducedprice) values (57, 'Soup - Campbells Beef Strogonoff', 31.41, 14.141);
insert into product (productid, productname, price, reducedprice) values (58, 'Spinach - Baby', 84.21, 9.421);
insert into product (productid, productname, price, reducedprice) values (59, 'Bread - Granary Small Pull', 55.69, 53.569);
insert into product (productid, productname, price, reducedprice) values (60, 'Beans - Soya Bean', 67.7, 30.77);
insert into product (productid, productname, price, reducedprice) values (61, 'Coffee Caramel Biscotti', 14.58, 3.458);
insert into product (productid, productname, price, reducedprice) values (62, 'Flour - Pastry', 40.82, 40.082);
insert into product (productid, productname, price, reducedprice) values (63, 'Iced Tea - Lemon, 340ml', 81.87, 34.187);
insert into product (productid, productname, price, reducedprice) values (64, 'Mustard - Dijon', 50.2, 21.02);
insert into product (productid, productname, price, reducedprice) values (65, 'Coffee - Decafenated', 49.66, 16.966);
insert into product (productid, productname, price, reducedprice) values (66, 'Lamb - Shoulder', 28.53, 16.853);
insert into product (productid, productname, price, reducedprice) values (67, 'Ice - Clear, 300 Lb For Carving', 42.04, 34.204);
insert into product (productid, productname, price, reducedprice) values (68, 'Sugar - Individual Portions', 38.16, 23.816);
insert into product (productid, productname, price, reducedprice) values (69, 'Cookie Dough - Chocolate Chip', 87.77, 22.777);
insert into product (productid, productname, price, reducedprice) values (70, 'Liners - Baking Cups', 28.48, 16.848);
insert into product (productid, productname, price, reducedprice) values (71, 'Paste - Black Olive', 8.43, 3.843);
insert into product (productid, productname, price, reducedprice) values (72, 'Nut - Almond, Blanched, Sliced', 49.55, 23.955);
insert into product (productid, productname, price, reducedprice) values (73, 'Salmon - Fillets', 98.27, 86.827);
insert into product (productid, productname, price, reducedprice) values (74, 'Vodka - Lemon, Absolut', 52.62, 21.262);
insert into product (productid, productname, price, reducedprice) values (75, 'Tea Leaves - Oolong', 97.35, 9.735);
insert into product (productid, productname, price, reducedprice) values (76, 'Cheese - Le Cru Du Clocher', 36.34, 13.634);
insert into product (productid, productname, price, reducedprice) values (77, 'Tea - Decaf Lipton', 40.85, 20.085);
insert into product (productid, productname, price, reducedprice) values (78, 'Tumeric', 24.43, 22.443);
insert into product (productid, productname, price, reducedprice) values (79, 'Chocolate - Mi - Amere Semi', 32.42, 27.242);
insert into product (productid, productname, price, reducedprice) values (80, 'Avocado', 25.98, 3.598);
insert into product (productid, productname, price, reducedprice) values (81, 'Triple Sec - Mcguinness', 40.0, 4.0);
insert into product (productid, productname, price, reducedprice) values (82, 'Beef - Salted', 28.3, 9.83);
insert into product (productid, productname, price, reducedprice) values (83, 'Nantucket - Carrot Orange', 7.24, 2.724);
insert into product (productid, productname, price, reducedprice) values (84, 'Chocolate Bar - Coffee Crisp', 4.91, 4.491);
insert into product (productid, productname, price, reducedprice) values (85, 'Pastry - Mini French Pastries', 99.02, 59.902);
insert into product (productid, productname, price, reducedprice) values (86, 'Cream - 10%', 58.84, 12.884);
insert into product (productid, productname, price, reducedprice) values (87, 'Beef - Kindney, Whole', 60.49, 18.049);
insert into product (productid, productname, price, reducedprice) values (88, 'Banana Turning', 54.72, 37.472);
insert into product (productid, productname, price, reducedprice) values (89, 'Nut - Macadamia', 83.44, 53.344);
insert into product (productid, productname, price, reducedprice) values (90, 'Lamb - Pieces, Diced', 46.78, 12.678);
insert into product (productid, productname, price, reducedprice) values (91, 'Oil - Avocado', 59.39, 5.939);
insert into product (productid, productname, price, reducedprice) values (92, 'Chicken - Tenderloin', 3.1, 0.31);
insert into product (productid, productname, price, reducedprice) values (93, 'Crush - Cream Soda', 62.32, 27.232);
insert into product (productid, productname, price, reducedprice) values (94, 'Sugar - Sweet N Low, Individual', 73.99, 17.399);
insert into product (productid, productname, price, reducedprice) values (95, 'Melon - Honey Dew', 92.93, 48.293);
insert into product (productid, productname, price, reducedprice) values (96, 'Chocolate - Sugar Free Semi Choc', 85.81, 54.581);
insert into product (productid, productname, price, reducedprice) values (97, 'Lamb - Loin, Trimmed, Boneless', 97.99, 75.799);
insert into product (productid, productname, price, reducedprice) values (98, 'Petite Baguette', 39.6, 37.96);
insert into product (productid, productname, price, reducedprice) values (99, 'Aromat Spice / Seasoning', 22.1, 6.21);
insert into product (productid, productname, price, reducedprice) values (100, 'Beer - Blue', 18.3, 17.83);
insert into product (productid, productname, price, reducedprice) values (101, 'Cheese - Manchego, Spanish', 3.51, 3.351);
insert into product (productid, productname, price, reducedprice) values (102, 'Pasta - Tortellini, Fresh', 51.94, 47.194);
