insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'English', 'Exam',0.79);
insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'Biology', 'Essay', 0.611);
insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'Physics', 'Essay', 0.667);
insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'Chemistry', 'Exam', 0.772);
insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'Maths', 'Essay', 0.422);
insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'History', 'Exam', 0.579);
insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'Religious Studies', 'Essay', 0.431);
insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'PE', 'Exam', 0.731);
insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'Geography', 'Exam', 0.848);
insert into subject (subjectid, topic, assessment, passrate) values (NEXTVAL('subjectID_seq'), 'English', 'Exam', 0.926);