drop table if exists accounts;

create table accounts
(
    id      int GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR (100) NOT NULL,
    balance dec(15, 2) NOT NULL,
    PRIMARY KEY (id)
);

insert into accounts (name,balance) VALUES ('Bob', 10000);
insert into accounts (name,balance) VALUES ('Alice', 10000);

-- check the accounts table for data
select * FROM accounts;